---
title: "New Class Enrollment"
author: "Brian Kim"
date: "03/03/2020"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(readxl)
library(tidyverse)
library(janitor)
library(reprex)
library(utils)
library(googlesheets4)
library(fs)
library(ggpubr)

```

```{r download_data, include =FALSE}

# download file using download.file()


url_current <- "https://registrar.fas.harvard.edu/files/fas-registrar/files/class_enrollment_summary_by_term_2.25.20_0.xlsx"

url_old <- "https://registrar.fas.harvard.edu/files/fas-registrar/files/class_enrollment_summary_by_term_3.22.19_0.xlsx"

# destfile assumes you're already in the directory, so you're just specifying
# how you want to call the downloaded file

# download.file(url = url_current, destfile = "current.xlsx")
# 
# download.file(url = url_old, destfile = "old.xlsx")


# read the excel file into the environment


current <- read_excel("class_enrollment_summary_by_term_2.25.20_0.xlsx", 
                skip = 3) %>%
  clean_names() %>%
  
  # filter out NA observations in course_name
  
  filter(! is.na(course_name))


# do it for old

old <- read_excel("class_enrollment_summary_by_term_3.22.19_0.xlsx", 
                  skip = 3) %>%
  clean_names() %>%
  filter(! is.na(course_name)) %>%
  select(course_id)

```


```{r, echo = FALSE}


# Bring the data together, using course_id, but only keep courses which are
# new this year, meaning that course_id did not exist in spring 2019

x <- current %>%
  anti_join(old, by = "course_id")


# figure out five largest courses

top5 <- x %>%
  arrange(desc(total)) %>%
  select(course_name, total) %>%
  slice(1:5)

```

```{r, echo = FALSE}

# Visualisation of the Five Largest Courses

graphtop5 <- ggplot(top5, aes(x = course_name, y = total)) + 
  geom_bar(stat = "identity") + 
  theme_classic() +
  theme(axis.text.x=element_text(angle = -45, hjust = 0)) + 
  labs(
    title = "Top 5 Course Enrollment", 
    subtitle = "As of February 25, 2020", 
    caption = "Data from Harvard Registrar's Office", 
    y = "Number of Students", x = "Course Name"
  )


graphtop5 %>%
  ggexport(filename = "graphtop5.png")

```